import React from 'react';
import { Plus, Star, Trash2 } from 'lucide-react';

export default function ReviewsView() {
  const [products, setProducts] = React.useState([]); const [reviews, setReviews] = React.useState([]); const [form, setForm] = React.useState({ product_id: '', reviewer_name: '', rating: 5, comment: '', created_at: '' }); const [message, setMessage] = React.useState('');
  const load = React.useCallback(async () => { const [p, r] = await Promise.all([fetch('/api/products?limit=100'), fetch('/api/reviews?limit=100')]); setProducts((await p.json()).rows || []); setReviews((await r.json()).rows || []); }, []);
  React.useEffect(() => { load().catch(() => setMessage('Reviews could not be loaded.')); }, [load]);
  const submit = async (event) => { event.preventDefault(); setMessage(''); const rating = Number(form.rating); if (!Number.isFinite(rating) || rating < 1 || rating > 5) return setMessage('Rating must be between 1.0 and 5.0.'); const response = await fetch('/api/reviews', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, product_id: Number(form.product_id), rating, source: 'manual', created_at: form.created_at || undefined }) }); if (!response.ok) return setMessage((await response.json()).message || 'Review could not be saved.'); setForm({ product_id: '', reviewer_name: '', rating: 5, comment: '', created_at: '' }); setMessage('Review saved.'); load(); };
  const remove = async (id) => { if (!window.confirm('Delete this review?')) return; await fetch(`/api/reviews/${id}`, { method: 'DELETE' }); load(); };
  const productName = (id) => products.find((product) => String(product.id) === String(id))?.name || `Product #${id}`;
  return <div className="space-y-5"><div><h2 className="text-2xl font-black text-slate-900">Customer Reviews</h2><p className="text-xs text-slate-500">Create, review, and remove storefront product reviews.</p></div>{message && <p className="rounded-xl bg-slate-100 p-3 text-xs font-bold">{message}</p>}<form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 sm:grid-cols-2"><select required value={form.product_id} onChange={(e) => setForm({ ...form, product_id: e.target.value })} className="rounded-xl border p-3 text-xs"><option value="">Select product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select><input required value={form.reviewer_name} onChange={(e) => setForm({ ...form, reviewer_name: e.target.value })} placeholder="Reviewer name" className="rounded-xl border p-3 text-xs"/><label className="text-xs font-bold">Rating (1.0–5.0)<input required type="number" min="1" max="5" step="0.1" value={form.rating} onChange={(e) => setForm({ ...form, rating: e.target.value })} className="mt-1 w-full rounded-xl border p-3 text-xs" placeholder="e.g. 4.8"/></label><input type="date" value={form.created_at} onChange={(e) => setForm({ ...form, created_at: e.target.value })} className="rounded-xl border p-3 text-xs"/><textarea required value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} placeholder="Review comment" className="min-h-24 rounded-xl border p-3 text-xs sm:col-span-2"/><button className="inline-flex w-fit items-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-xs font-bold text-white"><Plus size={15}/> Save review</button></form><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-3">Product</th><th className="p-3">Reviewer</th><th className="p-3">Rating</th><th className="p-3">Comment</th><th className="p-3"/></tr></thead><tbody>{reviews.map((review) => <tr key={review.id} className="border-t"><td className="p-3 font-bold">{productName(review.product_id)}</td><td className="p-3">{review.reviewer_name}</td><td className="p-3"><span className="inline-flex items-center gap-1"><Star size={13} className="fill-amber-400 text-amber-400"/>{Number(review.rating).toFixed(1)}</span></td><td className="max-w-md p-3">{review.comment}</td><td className="p-3"><button onClick={() => remove(review.id)} className="text-red-600"><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div>;
}
