import React from 'react';

const fallbackSlides = [
  { id: 1, badge: 'Limited time!', title: 'Get Special Offer', offerPrefix: 'Up to', offerMain: '40%', terms: 'All Services Available | T&C Applied', cta: 'Claim', image: 'https://images.unsplash.com/photo-1520045892732-304bc3ac5d8e?auto=format&fit=crop&w=1600&q=85' },
  { id: 2, badge: 'New season', title: 'Exclusive Gadgets Deal', offerPrefix: 'Up to', offerMain: '50%', terms: 'Free Shipping Nationwide | T&C Applied', cta: 'Claim', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=85' },
  { id: 3, badge: 'Hot offer', title: 'Top Accessories Upgrade', offerPrefix: 'Up to', offerMain: '35%', terms: 'Cash on Delivery Available | T&C Applied', cta: 'Claim', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=85' }
];

export default function HeroBanner({ slides = [] }) {
  const [liveBanners, setLiveBanners] = React.useState([]);
  const [bannersLoaded, setBannersLoaded] = React.useState(false);
  const [currentSlide, setCurrentSlide] = React.useState(0);
  React.useEffect(() => { let active = true; Promise.all([fetch('/api/banners?limit=50'), fetch('/api/promotions?limit=50')]).then(async ([websiteResponse, appResponse]) => { const website = websiteResponse.ok ? await websiteResponse.json() : { rows: [] }; const app = appResponse.ok ? await appResponse.json() : { rows: [] }; const today = new Date().toISOString().slice(0, 10); const websiteRows = (website.rows || []).filter((row) => row.image_url && String(row.status || 'Active').toLowerCase() === 'active' && (!row.start_date || String(row.start_date).slice(0, 10) <= today) && (!row.end_date || String(row.end_date).slice(0, 10) >= today)); const appRows = (app.rows || []).filter((row) => row.image_url && String(row.status || 'Active').toLowerCase() === 'active' && String(row.show_on_website || 'Yes').toLowerCase() === 'yes' && (!row.valid_from || String(row.valid_from).slice(0, 10) <= today) && (!row.valid_till || String(row.valid_till).slice(0, 10) >= today)); const rows = [...websiteRows, ...appRows]; if (active) { setLiveBanners(rows.map((row) => ({ id: `${row.name ? 'app' : 'website'}-${row.id}`, title: row.title || row.name || 'Elistin promotion', image: row.image_url, link: row.link || null, imageOnly: true }))); setBannersLoaded(true); } }).catch(() => { if (active) { setLiveBanners([]); setBannersLoaded(true); } }); return () => { active = false; }; }, []);
  const supplied = slides.map((slide) => ({ id: slide.id, badge: slide.badge || 'Limited time!', title: slide.subtitle || slide.title, offerPrefix: slide.offerPrefix || 'Up to', offerMain: slide.offerMain || '40%', terms: slide.terms || 'All Services Available | T&C Applied', cta: slide.cta || 'Claim', image: slide.image, link: slide.link }));
  const activeSlides = bannersLoaded ? liveBanners : (supplied.length ? supplied : fallbackSlides);
  React.useEffect(() => { setCurrentSlide(0); if (activeSlides.length < 2) return undefined; const timer = window.setInterval(() => setCurrentSlide((value) => (value + 1) % activeSlides.length), 4500); return () => window.clearInterval(timer); }, [activeSlides.length]);
  const slide = activeSlides[currentSlide] || activeSlides[0]; const showProducts = () => document.getElementById('products-section')?.scrollIntoView({ behavior: 'smooth' }); const handleCta = () => slide.link ? window.location.assign(slide.link) : showProducts(); if (bannersLoaded && !slide) return null;
  return <section className="mx-auto w-full max-w-7xl px-3 pt-2 sm:px-4 lg:px-6"><div className="mb-2 flex items-center justify-between"><h2 className="text-base font-black tracking-tight text-slate-900 sm:text-lg">#SpecialForYou</h2><button type="button" onClick={showProducts} className="text-xs font-bold text-[#E8262A] sm:text-sm">See All</button></div><div className="relative mx-auto max-w-6xl overflow-hidden rounded-[26px] border border-slate-200 bg-slate-900 shadow-lg"><div className="relative h-[220px] sm:h-[280px] md:h-[320px]"><img key={slide.id} src={slide.image} alt={slide.title} className="absolute inset-0 h-full w-full object-cover object-center transition duration-700"/>{!slide.imageOnly && <><div className="absolute inset-0 bg-gradient-to-r from-slate-950/75 via-slate-950/35 to-transparent"/><div className="absolute inset-x-0 bottom-0 h-[23%] bg-slate-950/45"/><div className="absolute left-[5%] top-[12%] z-10"><span className="inline-flex rounded-full bg-white px-4 py-2 text-[11px] font-black text-slate-900 sm:text-sm">{slide.badge}</span><h3 className="mt-7 max-w-[75%] text-2xl font-black leading-tight text-white sm:text-4xl">{slide.title}</h3><div className="mt-2 flex items-end gap-2 text-white"><span className="mb-1 text-sm font-bold sm:text-lg">{slide.offerPrefix}</span><strong className="text-5xl leading-none sm:text-7xl">{slide.offerMain}</strong></div></div><p className="absolute bottom-[7%] left-[5%] z-10 max-w-[60%] truncate text-[9px] font-medium text-white/85 sm:text-sm">{slide.terms}</p><button type="button" onClick={handleCta} className="absolute bottom-[5%] right-[5%] z-10 rounded-full bg-[#ff3d50] px-6 py-3 text-sm font-black text-white shadow-lg hover:bg-red-600 sm:px-9 sm:py-4 sm:text-lg">{slide.cta}</button></>}{activeSlides.length > 1 && <div className="absolute bottom-3 left-1/2 z-20 flex -translate-x-1/2 gap-2">{activeSlides.map((item, index) => <button key={item.id || index} aria-label={`Show banner ${index + 1}`} onClick={() => setCurrentSlide(index)} className={`h-2.5 rounded-full shadow-sm ${currentSlide === index ? 'w-7 bg-[#ff3d50]' : 'w-2.5 bg-white/80'}`}/>)}</div>}</div></div></section>;
}
