import React from 'react';
import { Plus, Search, X, MoreVertical, Edit2, Trash2, PlusCircle } from 'lucide-react';
import { useAdmin } from '../../context/AdminContext';

const emptyStock = { productId: '', totalItems: '', stockBelongTo: '', quantity: '', description: '' };

export default function StockManagement() {
  const { stockRecords, products, addStockRecord, deleteStockRecord } = useAdmin();
  const [query, setQuery] = React.useState(''); const [open, setOpen] = React.useState(false); const [menuId, setMenuId] = React.useState(null); const [mode, setMode] = React.useState('add'); const [form, setForm] = React.useState(emptyStock);
  const rows = products.map((product) => { const latest = stockRecords.find((row) => String(row.productId) === String(product.id)); const remaining = Number(product.stock) || 0; const total = Number(latest?.totalItems ?? remaining) || 0; return { id: latest?.id || `product-${product.id}`, productId: product.id, sku: product.sku || '—', productName: product.name, soldItems: Math.max(0, total - remaining), quantity: remaining, remaining, description: latest?.description || product.description || '', product }; }).filter((row) => [row.productId, row.productName, row.product.category, row.description].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase())));
  const openForm = (row, nextMode = 'add') => { setMode(nextMode); setForm(nextMode === 'add' ? emptyStock : { productId: row.productId, totalItems: row.quantity, stockBelongTo: row.product?.seller || '', quantity: nextMode === 'add-more' ? '' : row.quantity, description: row.description || '' }); setMenuId(null); setOpen(true); };
  const submit = (event) => { event.preventDefault(); const row = rows.find((item) => String(item.productId) === String(form.productId)); addStockRecord({ ...form, totalItems: mode === 'add-more' ? Number(row?.quantity || 0) + Number(form.quantity || 0) : form.totalItems }); setForm(emptyStock); setOpen(false); };
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black text-slate-900">Stock / Inventory</h2><p className="text-xs font-medium text-slate-500">Product-wise stock ownership, totals, quantities and descriptions.</p></div><button onClick={() => openForm()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-xs font-bold text-white"><Plus size={16}/> Add Stock</button></div>
    <div className="flex items-center gap-3 rounded-2xl border bg-white p-4"><Search size={16} className="text-slate-400"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search Product ID, product, seller..." className="w-full bg-transparent text-xs font-semibold outline-none"/></div>
    <div className="overflow-visible rounded-2xl border bg-white"><div className="overflow-visible"><table className="w-full text-left text-xs"><thead className="bg-slate-900 text-[10px] font-bold uppercase text-white"><tr>{['SKU','Product Image / Name','Sold Items','Category','Quantity','Remaining','Actions'].map((h)=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row)=> <tr key={row.id} className="hover:bg-rose-50/40"><td className="p-4 font-black">{row.sku}</td><td className="p-4"><div className="flex items-center gap-3 font-bold"><img src={row.product?.image || 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&q=80'} alt={row.productName} className="h-10 w-10 rounded-lg border object-cover"/><span>{row.productName}</span></div></td><td className="p-4">{row.soldItems}</td><td className="p-4">{row.product?.category || '—'}</td><td className="p-4 font-black text-emerald-700">{row.quantity}</td><td className="p-4 font-black text-sky-700">{row.remaining}</td><td className="relative p-4"><button type="button" onClick={()=>setMenuId(menuId===row.id?null:row.id)} className="rounded-lg border border-rose-200 p-2 text-rose-600 hover:bg-rose-50"><MoreVertical size={16}/></button>{menuId===row.id&&<div className="absolute right-4 bottom-12 z-30 w-40 rounded-xl border border-rose-100 bg-white p-1.5 shadow-xl"><button type="button" onClick={()=>openForm(row,'edit')} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-bold hover:bg-rose-50"><Edit2 size={14}/> Edit</button><button type="button" onClick={()=>openForm(row,'add-more')} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-bold text-emerald-700 hover:bg-emerald-50"><PlusCircle size={14}/> Add Stock</button><button type="button" onClick={()=>{if(window.confirm('Remove this stock?')) deleteStockRecord(row);setMenuId(null)}} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-bold text-rose-600 hover:bg-rose-50"><Trash2 size={14}/> Delete</button></div>}</td></tr>)}</tbody></table></div></div>
    {open && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><div><h3 className="text-lg font-black">{mode === 'add-more' ? 'Add Stock Quantity' : mode === 'edit' ? 'Edit Stock' : 'Add Stock'}</h3><p className="text-xs text-slate-500">{mode === 'add-more' ? 'Enter quantity to add to current stock.' : 'Enter inventory details.'}</p></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Product ID *<select required disabled={mode !== 'add'} value={form.productId} onChange={(e)=>setForm({...form,productId:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"><option value="">Select product</option>{products.map((p)=><option key={p.id} value={p.id}>{p.id} — {p.name}</option>)}</select></label>{mode !== 'add-more' && <><label className="text-xs font-bold">Total Items *<input type="number" min="0" required value={form.totalItems} onChange={(e)=>setForm({...form,totalItems:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label><label className="text-xs font-bold">Stock Belong To *<input required value={form.stockBelongTo} onChange={(e)=>setForm({...form,stockBelongTo:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label></>}<label className="text-xs font-bold">{mode === 'add-more' ? 'Quantity to Add *' : 'Quantity *'}<input type="number" min="1" required value={form.quantity} onChange={(e)=>setForm({...form,quantity:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label>{mode !== 'add-more' && <label className="text-xs font-bold sm:col-span-2">Description *<textarea required rows="3" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5"/></label>}</div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2 text-xs font-bold">Cancel</button><button className="rounded-xl bg-red-600 px-4 py-2 text-xs font-bold text-white">Save Stock</button></div></form></div>}
  </div>;
}
